---
# RBAC related
apiVersion: v1
kind: ServiceAccount
metadata:
  name: igniter-sa
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: igniter-role
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: igniter-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: igniter-role
subjects:
  - kind: ServiceAccount
    name: igniter-sa
    namespace: kube-system
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: igniter-deployment
  namespace: kube-system
  labels:
    k8s-app: igniter
spec:
  replicas: 1  # Never run more than 1 replica, this will lead to race conditions
  selector:
    matchLabels:
      k8s-app: igniter
  template:
    metadata:
      labels:
        k8s-app: igniter
        name: igniter
    spec:
      serviceAccountName: igniter-sa
      terminationGracePeriodSeconds: 60
      containers:
        - image: worldiety/igniter
          name: igniter-container
          env:
            - name: "CLOUDFLARE_API_TOKEN"
              valueFrom:
                secretKeyRef:
                  name: cloudflare-api-token
                  key: token
            - name: "CLOUDFLARE_ZONE"
              value: ""  # Add cloudflare zone here
---
